const colors = {
  light: {
    text: '#1a1030',
    tint: '#667eea',
    background: '#f5f3ff',
    foreground: '#1a1030',
    card: '#ffffff',
    cardForeground: '#1a1030',
    primary: '#667eea',
    primaryForeground: '#ffffff',
    secondary: '#764ba2',
    secondaryForeground: '#ffffff',
    muted: '#f3f0ff',
    mutedForeground: '#6b7280',
    accent: '#e9d5ff',
    accentForeground: '#4c1d95',
    destructive: '#ef4444',
    destructiveForeground: '#ffffff',
    border: '#e5e7eb',
    input: '#e5e7eb',
    success: '#22c55e',
    successForeground: '#ffffff',
    warning: '#f59e0b',
    warningForeground: '#ffffff',
    gradientStart: '#667eea',
    gradientEnd: '#764ba2',
    serverRunning: '#22c55e',
    serverStopped: '#6b7280',
  },
  dark: {
    text: '#f0eeff',
    tint: '#818cf8',
    background: '#0f0a1e',
    foreground: '#f0eeff',
    card: '#1a1030',
    cardForeground: '#f0eeff',
    primary: '#667eea',
    primaryForeground: '#ffffff',
    secondary: '#764ba2',
    secondaryForeground: '#ffffff',
    muted: '#1f1540',
    mutedForeground: '#9ca3af',
    accent: '#2d1f4e',
    accentForeground: '#c4b5fd',
    destructive: '#ef4444',
    destructiveForeground: '#ffffff',
    border: '#2d1f4e',
    input: '#2d1f4e',
    success: '#22c55e',
    successForeground: '#ffffff',
    warning: '#f59e0b',
    warningForeground: '#ffffff',
    gradientStart: '#667eea',
    gradientEnd: '#764ba2',
    serverRunning: '#22c55e',
    serverStopped: '#6b7280',
  },
  radius: 14,
};

export default colors;
